
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import BeanClasses.EmployeeBean;
import DBManager.DBM;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Waseem
 */
public class EmployeeLoan extends javax.swing.JFrame {
Vector v = null;
static int employeeId;
    /**
     * Creates new form Loan
     */
    public EmployeeLoan(int employeeId)throws Exception {
        initComponents();
     v = DBM.getEmployee(employeeId);
        setBounds(0,0,700,560);
         list.setListData(v);
        list.setSelectedIndex(0);
        if(list.getSelectedIndex()==0){
         EmployeeBean bean = (EmployeeBean)list.getSelectedValue();
        empid.setText(bean.getEmpId());
        empnam.setText(bean.getEmpName());
        empfname.setText(bean.getEmpFname());
        empsurname.setText(bean.getEmpSurname());
        ImageIcon image = bean.getImg();
        Image im = image.getImage();
        Image myImg=im.getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon newImage = new ImageIcon(myImg);
        imagelabel.setIcon(newImage);
        }
       
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        empid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        empnam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        empfname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        empsurname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        installment = new javax.swing.JTextField();
        loanamoount = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        loandate = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        loanduration = new javax.swing.JComboBox<>();
        imagelabel = new javax.swing.JLabel();

        list.setFont(new java.awt.Font("Dialog", 0, 14));
        list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loan");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Employee ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 80, 113, 35);

        empid.setEditable(false);
        empid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empidActionPerformed(evt);
            }
        });
        jPanel1.add(empid);
        empid.setBounds(140, 80, 219, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 130, 113, 35);

        empnam.setEditable(false);
        empnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empnamActionPerformed(evt);
            }
        });
        jPanel1.add(empnam);
        empnam.setBounds(140, 130, 219, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Father Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 180, 113, 35);

        empfname.setEditable(false);
        empfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empfnameActionPerformed(evt);
            }
        });
        jPanel1.add(empfname);
        empfname.setBounds(140, 180, 219, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Surname");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 230, 113, 35);

        empsurname.setEditable(false);
        empsurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empsurnameActionPerformed(evt);
            }
        });
        jPanel1.add(empsurname);
        empsurname.setBounds(140, 230, 219, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Date");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 280, 113, 35);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Loan Duration");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 380, 113, 35);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Installment");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 430, 113, 35);

        installment.setEditable(false);
        installment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                installmentActionPerformed(evt);
            }
        });
        jPanel1.add(installment);
        installment.setBounds(140, 430, 219, 30);

        loanamoount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanamoountActionPerformed(evt);
            }
        });
        loanamoount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loanamoountKeyTyped(evt);
            }
        });
        jPanel1.add(loanamoount);
        loanamoount.setBounds(140, 330, 219, 30);

        back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(100, 480, 70, 31);
        jPanel1.add(loandate);
        loandate.setBounds(140, 280, 220, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Clear");
        jPanel1.add(jButton3);
        jButton3.setBounds(300, 480, 70, 31);

        submit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        submit.setText("Apply");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(510, 480, 70, 31);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Loan Amount");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 330, 113, 35);

        loanduration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Duration", "6 Month", "12 Month" }));
        loanduration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loandurationActionPerformed(evt);
            }
        });
        jPanel1.add(loanduration);
        loanduration.setBounds(140, 380, 220, 30);

        imagelabel.setBackground(new java.awt.Color(0, 0, 0));
        imagelabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Waseem\\Documents\\NetBeansProjects\\FYP\\x.png")); // NOI18N
        imagelabel.setText("jLabel17");
        jPanel1.add(imagelabel);
        imagelabel.setBounds(420, 80, 190, 250);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listValueChanged
       

    }//GEN-LAST:event_listValueChanged

    private void empidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empidActionPerformed

    private void empnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empnamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empnamActionPerformed

    private void empfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empfnameActionPerformed

    private void empsurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empsurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empsurnameActionPerformed

    private void installmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_installmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_installmentActionPerformed

    private void loanamoountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanamoountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanamoountActionPerformed

    private void loanamoountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loanamoountKeyTyped
       eventClass eC = new eventClass();
       eC.integerEvent(evt);
    }//GEN-LAST:event_loanamoountKeyTyped

    private void loandurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loandurationActionPerformed

        String selectedDuration = (String)loanduration.getSelectedItem();
       
         if(selectedDuration.equals("6 Month")){
        installment.setText(null);
        int totalMonth = 6;
        String loanAmount = loanamoount.getText();double totalAmount = Integer.parseInt(loanAmount);
        double balance = totalAmount/totalMonth;
        installment.setText(balance+""); 
        
        }
        else if (selectedDuration.equals("12 Month")){
        installment.setText(null);
        int totalMonth = 12;
        String loanAmount = loanamoount.getText();double totalAmount = Integer.parseInt(loanAmount);
        double balance = totalAmount/totalMonth;
        installment.setText(balance+""); 
        
        }
        
        
    }//GEN-LAST:event_loandurationActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try{
        EmployeeBean bean = (EmployeeBean)list.getSelectedValue();
        int basicSalary = bean.getBasicSalary()/2;//basicsalary devide by 2
        double oldInstallments = DBM.getInstallment(bean.getEmployeeId());
        double newInstallments = Double.valueOf(installment.getText());
        int loanInfo = DBM.loanInfo(bean.getEmployeeId());
       // System.out.println(loanInfo + " info");
        if(loanInfo>0){
        JOptionPane.showMessageDialog(null,"Old Loan Is Not Paid Yet");
        }
        else{
       
        
        double allInstallments = oldInstallments+newInstallments;
        if(allInstallments>=basicSalary){
        JOptionPane.showMessageDialog(null,"Not Approved");
        }
        else{
         DateFormat fmt = new SimpleDateFormat("yyyy-MM-d");
         String date = fmt.format(this.loandate.getDate()); //jdatechooser
         String loanAmount = loanamoount.getText();int totalAmount = Integer.parseInt(loanAmount);
         String totalInstalment = installment.getText();double totlInstallment = Double.valueOf(totalInstalment);
       
             int rows = DBM.addLoan(bean.getEmployeeId(), date, totalAmount, totalAmount,totlInstallment);
            
                 JOptionPane.showMessageDialog(null,"Successfully Loan Added");
        }
        }
         }catch(Exception e){e.printStackTrace();}
    }//GEN-LAST:event_submitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
         EmployeeLoan.this.setVisible(false);
        try {
            new SearchEmployee().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EmployeeLoan(employeeId).setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(EmployeeLoan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField empfname;
    private javax.swing.JTextField empid;
    private javax.swing.JTextField empnam;
    private javax.swing.JTextField empsurname;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JTextField installment;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list;
    private javax.swing.JTextField loanamoount;
    private com.toedter.calendar.JDateChooser loandate;
    private javax.swing.JComboBox<String> loanduration;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
